name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - justeraseme
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox (and it's forks)
        - Chrome (and some of it's forks)
        - Safari
        - Microsoft Edge
        - Brave
        - Opera
        - Not listed here
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device are you on?
      multiple: false
      options:
        - Desktop device (Windows, Mac OS & Linux)
        - Small mobile device (phone, small console)
        - Large mobile device (tablet)
        - Console (please specify which one below)
        - Legacy device
        - Not listed here
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: More context
      description: Please provide more context.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Required textboxes
      description: By submitting this issue, you must agree to these checkboxes.
      options:
        - label: I agree to be respectful when resolving this issue
          required: false
        - label: I am willing to follow up and provide more details if requested
          required: false
        - label: I am aware that some obscure setups, such as outdated web browsers and devices and legacy setups may not be resolved
          required: false
        - label: I was not truthful to the above checkboxes
          required: false

