name: Feature request
description: File a feature request.
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - justeraseme
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: what-add
    attributes:
      label: What would you like to see?
      description: Tell me more about what you want to see implimented!
      placeholder: Give us some information!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: More context
      description: Please provide more context.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Required textboxes
      description: By submitting this issue, you must agree to these checkboxes.
      options:
        - label: I agree to be respectful when resolving this issue
          required: false
        - label: I am willing to follow up and provide more details if requested
          required: false
        - label: I am aware that the issue may be closed prematurely if I conclude that the feature is too much to implement with my current knowledge
          required: false
        - label: I was not truthful to the above checkboxes
          required: false

